<a href="https://colab.research.google.com/github/Tharul-Fernando/CM2604-Telco-Customer-Churn/blob/main/02_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np

# Load Original Dataset
file_path = ("/content/drive/MyDrive/ML_Coursework/data/WA_Fn-UseC_-Telco-Customer-Churn.csv")

df = pd.read_csv(file_path)

# Keep the original data unchanged
df_clean = df.copy()

print("Dataset shape:", df_clean.shape)
display(df_clean.head())

Dataset shape: (7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
# Convert TotalCharges from text to numerical values
df_clean["TotalCharges"] = pd.to_numeric(df_clean["TotalCharges"], errors="coerce")

# Check the new data type
print("Data types:", df_clean["TotalCharges"].dtypes)

# Count missing values after conversion
print("Missing TotalCharges:", df_clean["TotalCharges"].isnull().sum())

Data types: float64
Missing TotalCharges: 11

In [7]:
# Examine customers with missing values
missing_rows = df_clean[df_clean["TotalCharges"].isnull()]

print("Number of affected customers:", len(missing_rows))

print("Tenure values:", missing_rows["tenure"].unique())

display(missing_rows[["tenure","MonthlyCharges","TotalCharges","Churn"]])

Number of of affected customers: 11
Tenure values: [0]

      tenure  MonthlyCharges  TotalCharges Churn
488        0           52.55           NaN    No
753        0           20.25           NaN    No
936        0           80.85           NaN    No
1082       0           25.75           NaN    No
1340       0           56.05           NaN    No
3331       0           19.85           NaN    No
3826       0           25.35           NaN    No
4380       0           20.00           NaN    No
5218       0           19.70           NaN    No
6670       0           73.35           NaN    No
6754       0           61.90           NaN    No

In [11]:
# Replace missing TotalCharges values with zero
df_clean["TotalCharges"] = df_clean["TotalCharges"].fillna(0)

# Verify that no missing values remain
print("Missing TotalCharges:", df_clean["TotalCharges"].isnull().sum())

# Verify the datatype
print("Data type:",df_clean["TotalCharges"].dtypes)

# Check the dataset dimensions
print("Dataset shape:", df_clean.shape)

Missing TotalCharges: 0
Data type: float64
Dataset shape: (7043, 21)

### Preprocessing 1: Handling Missing TotalCharges Values

**Problem:** The TotalCharges column was stored as an object and contained 11 blank values, even though the initial null-value check detected no missing data.

**Action:** The column was converted to a numerical data type using `pd.to_numeric()` with `errors="coerce"`. The resulting 11 missing values `(NaN)` were then replaced with zero using `fillna(0)`.

**Justification:** All 11 affected customers had a tenure of zero months, suggesting they may not have accumulated any charges. Replacing the missing values with zero was considered a reasonable assumption, allowing all 7,043 customer records to be retained.